# Generated by Django 4.2.7 on 2023-11-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='nome_aula',
        ),
    ]
