# Generated by Django 4.2.4 on 2023-11-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topico',
            name='aula',
        ),
        migrations.AlterField(
            model_name='topico',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
